// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartAlarms.proto

package grpc.smartalarms;

public interface sensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor = 1;</code>
   */
  java.lang.String getSensor();
  /**
   * <code>string sensor = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorBytes();
}
