// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartAlarms.proto

package grpc.smartalarms;

public interface sensorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensorAlarm = 1;</code>
   */
  java.lang.String getSensorAlarm();
  /**
   * <code>string sensorAlarm = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorAlarmBytes();
}
