// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartAlarms.proto

package grpc.smartalarms;

public interface smokeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1;</code>
   */
  int getLatitude();

  /**
   * <code>int32 longtitude = 2;</code>
   */
  int getLongtitude();
}
