// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartAlarms.proto

package grpc.smartalarms;

/**
 * Protobuf type {@code smokeResponse}
 */
public  final class smokeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smokeResponse)
    smokeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use smokeResponse.newBuilder() to construct.
  private smokeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private smokeResponse() {
    smokeDetect_ = "";
    smokeLocations_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private smokeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            smokeDetect_ = s;
            break;
          }
          case 16: {

            smokeLocations_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.smartalarms.SmartAlarmsImpl.internal_static_smokeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.smartalarms.SmartAlarmsImpl.internal_static_smokeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.smartalarms.smokeResponse.class, grpc.smartalarms.smokeResponse.Builder.class);
  }

  public static final int SMOKEDETECT_FIELD_NUMBER = 1;
  private volatile java.lang.Object smokeDetect_;
  /**
   * <code>string smokeDetect = 1;</code>
   */
  public java.lang.String getSmokeDetect() {
    java.lang.Object ref = smokeDetect_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      smokeDetect_ = s;
      return s;
    }
  }
  /**
   * <code>string smokeDetect = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSmokeDetectBytes() {
    java.lang.Object ref = smokeDetect_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      smokeDetect_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SMOKELOCATIONS_FIELD_NUMBER = 2;
  private int smokeLocations_;
  /**
   * <code>int32 smokeLocations = 2;</code>
   */
  public int getSmokeLocations() {
    return smokeLocations_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSmokeDetectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, smokeDetect_);
    }
    if (smokeLocations_ != 0) {
      output.writeInt32(2, smokeLocations_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSmokeDetectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, smokeDetect_);
    }
    if (smokeLocations_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, smokeLocations_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.smartalarms.smokeResponse)) {
      return super.equals(obj);
    }
    grpc.smartalarms.smokeResponse other = (grpc.smartalarms.smokeResponse) obj;

    boolean result = true;
    result = result && getSmokeDetect()
        .equals(other.getSmokeDetect());
    result = result && (getSmokeLocations()
        == other.getSmokeLocations());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SMOKEDETECT_FIELD_NUMBER;
    hash = (53 * hash) + getSmokeDetect().hashCode();
    hash = (37 * hash) + SMOKELOCATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getSmokeLocations();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.smartalarms.smokeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartalarms.smokeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.smartalarms.smokeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartalarms.smokeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.smartalarms.smokeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smokeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smokeResponse)
      grpc.smartalarms.smokeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.smartalarms.SmartAlarmsImpl.internal_static_smokeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.smartalarms.SmartAlarmsImpl.internal_static_smokeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.smartalarms.smokeResponse.class, grpc.smartalarms.smokeResponse.Builder.class);
    }

    // Construct using grpc.smartalarms.smokeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      smokeDetect_ = "";

      smokeLocations_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.smartalarms.SmartAlarmsImpl.internal_static_smokeResponse_descriptor;
    }

    @java.lang.Override
    public grpc.smartalarms.smokeResponse getDefaultInstanceForType() {
      return grpc.smartalarms.smokeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.smartalarms.smokeResponse build() {
      grpc.smartalarms.smokeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.smartalarms.smokeResponse buildPartial() {
      grpc.smartalarms.smokeResponse result = new grpc.smartalarms.smokeResponse(this);
      result.smokeDetect_ = smokeDetect_;
      result.smokeLocations_ = smokeLocations_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.smartalarms.smokeResponse) {
        return mergeFrom((grpc.smartalarms.smokeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.smartalarms.smokeResponse other) {
      if (other == grpc.smartalarms.smokeResponse.getDefaultInstance()) return this;
      if (!other.getSmokeDetect().isEmpty()) {
        smokeDetect_ = other.smokeDetect_;
        onChanged();
      }
      if (other.getSmokeLocations() != 0) {
        setSmokeLocations(other.getSmokeLocations());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.smartalarms.smokeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.smartalarms.smokeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object smokeDetect_ = "";
    /**
     * <code>string smokeDetect = 1;</code>
     */
    public java.lang.String getSmokeDetect() {
      java.lang.Object ref = smokeDetect_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        smokeDetect_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string smokeDetect = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSmokeDetectBytes() {
      java.lang.Object ref = smokeDetect_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        smokeDetect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string smokeDetect = 1;</code>
     */
    public Builder setSmokeDetect(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      smokeDetect_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string smokeDetect = 1;</code>
     */
    public Builder clearSmokeDetect() {
      
      smokeDetect_ = getDefaultInstance().getSmokeDetect();
      onChanged();
      return this;
    }
    /**
     * <code>string smokeDetect = 1;</code>
     */
    public Builder setSmokeDetectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      smokeDetect_ = value;
      onChanged();
      return this;
    }

    private int smokeLocations_ ;
    /**
     * <code>int32 smokeLocations = 2;</code>
     */
    public int getSmokeLocations() {
      return smokeLocations_;
    }
    /**
     * <code>int32 smokeLocations = 2;</code>
     */
    public Builder setSmokeLocations(int value) {
      
      smokeLocations_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 smokeLocations = 2;</code>
     */
    public Builder clearSmokeLocations() {
      
      smokeLocations_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smokeResponse)
  }

  // @@protoc_insertion_point(class_scope:smokeResponse)
  private static final grpc.smartalarms.smokeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.smartalarms.smokeResponse();
  }

  public static grpc.smartalarms.smokeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<smokeResponse>
      PARSER = new com.google.protobuf.AbstractParser<smokeResponse>() {
    @java.lang.Override
    public smokeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new smokeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<smokeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<smokeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.smartalarms.smokeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

