// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartAlarms.proto

package grpc.smartalarms;

public interface smokeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string smokeDetect = 1;</code>
   */
  java.lang.String getSmokeDetect();
  /**
   * <code>string smokeDetect = 1;</code>
   */
  com.google.protobuf.ByteString
      getSmokeDetectBytes();

  /**
   * <code>int32 smokeLocations = 2;</code>
   */
  int getSmokeLocations();
}
