// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartAlarms.proto

package grpc.smartalarms;

public interface smokeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string smoke = 1;</code>
   */
  java.lang.String getSmoke();
  /**
   * <code>string smoke = 1;</code>
   */
  com.google.protobuf.ByteString
      getSmokeBytes();
}
