// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCameras.proto

package grpc.smartcameras;

public interface ringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ring = 1;</code>
   */
  java.lang.String getRing();
  /**
   * <code>string ring = 1;</code>
   */
  com.google.protobuf.ByteString
      getRingBytes();
}
