// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCameras.proto

package grpc.smartcameras;

public interface ringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string respond = 1;</code>
   */
  java.lang.String getRespond();
  /**
   * <code>string respond = 1;</code>
   */
  com.google.protobuf.ByteString
      getRespondBytes();
}
