// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCameras.proto

package grpc.smartcameras;

public interface videoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:videoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string watchVideo = 1;</code>
   */
  java.lang.String getWatchVideo();
  /**
   * <code>string watchVideo = 1;</code>
   */
  com.google.protobuf.ByteString
      getWatchVideoBytes();
}
