// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCameras.proto

package grpc.smartcameras;

public interface videoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:videoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string video = 1;</code>
   */
  java.lang.String getVideo();
  /**
   * <code>string video = 1;</code>
   */
  com.google.protobuf.ByteString
      getVideoBytes();
}
