// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartSafety.proto

package grpc.smartsafety;

public interface lightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightOff = 1;</code>
   */
  java.lang.String getLightOff();
  /**
   * <code>string lightOff = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightOffBytes();
}
