// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartSafety.proto

package grpc.smartsafety;

public final class SmartSafetyImpl {
  private SmartSafetyImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021smartSafety.proto\"\033\n\013lockRequest\022\014\n\004lo" +
      "ck\030\001 \001(\t\"\036\n\014lockResponse\022\016\n\006unlock\030\001 \001(\t" +
      "\"\037\n\014lightRequest\022\017\n\007lightOn\030\001 \001(\t\"!\n\rlig" +
      "htResponse\022\020\n\010lightOff\030\001 \001(\t2h\n\013smartSaf" +
      "ety\022*\n\tSmartLock\022\014.lockRequest\032\r.lockRes" +
      "ponse\"\000\022-\n\nSmartLight\022\r.lightRequest\032\016.l" +
      "ightResponse\"\000B%\n\020grpc.smartsafetyB\017Smar" +
      "tSafetyImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lockRequest_descriptor,
        new java.lang.String[] { "Lock", });
    internal_static_lockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lockResponse_descriptor,
        new java.lang.String[] { "Unlock", });
    internal_static_lightRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightRequest_descriptor,
        new java.lang.String[] { "LightOn", });
    internal_static_lightResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightResponse_descriptor,
        new java.lang.String[] { "LightOff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
