// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartSafety.proto

package grpc.newservice;

public interface lightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightOn = 1;</code>
   */
  java.lang.String getLightOn();
  /**
   * <code>string lightOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightOnBytes();
}
