// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartSafety.proto

package grpc.newservice;

public interface lockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lock = 1;</code>
   */
  java.lang.String getLock();
  /**
   * <code>string lock = 1;</code>
   */
  com.google.protobuf.ByteString
      getLockBytes();
}
