// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartSafety.proto

package grpc.newservice;

public interface lockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string unlock = 1;</code>
   */
  java.lang.String getUnlock();
  /**
   * <code>string unlock = 1;</code>
   */
  com.google.protobuf.ByteString
      getUnlockBytes();
}
